<a href="https://colab.research.google.com/github/krishnamanchikalapudi/examples.py/blob/develop/MiniProjects/S%26P_500_company_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Read S&P 500 company information from wikipedia

In [1]:
import pandas as pd

html = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
sp500Companies = html[0] # list 1st table data
sp500Companies

    Symbol             Security  ...      CIK      Founded
0      MMM           3M Company  ...    66740         1902
1      ABT  Abbott Laboratories  ...     1800         1888
2     ABBV          AbbVie Inc.  ...  1551152  2013 (1888)
3     ABMD          ABIOMED Inc  ...   815094         1981
4      ACN        Accenture plc  ...  1467373         1989
..     ...                  ...  ...      ...          ...
500    YUM      Yum! Brands Inc  ...  1041061         1997
501   ZBRA   Zebra Technologies  ...   877212         1969
502    ZBH        Zimmer Biomet  ...  1136869         1927
503   ZION        Zions Bancorp  ...   109380         1873
504    ZTS               Zoetis  ...  1555280         1952

[505 rows x 9 columns]

## Sort by Symbol

In [2]:
sp500Companies.sort_values("Symbol")

    Symbol                  Security  ...      CIK      Founded
11       A  Agilent Technologies Inc  ...  1090872         1999
28     AAL   American Airlines Group  ...     6201         1934
8      AAP        Advance Auto Parts  ...  1158449         1932
45    AAPL                Apple Inc.  ...   320193         1977
2     ABBV               AbbVie Inc.  ...  1551152  2013 (1888)
..     ...                       ...  ...      ...          ...
500    YUM           Yum! Brands Inc  ...  1041061         1997
502    ZBH             Zimmer Biomet  ...  1136869         1927
501   ZBRA        Zebra Technologies  ...   877212         1969
503   ZION             Zions Bancorp  ...   109380         1873
504    ZTS                    Zoetis  ...  1555280         1952

[505 rows x 9 columns]

## Sort by Central Index Key (CIK)

In [3]:
sp500Companies.sort_values("CIK")

    Symbol                      Security  ...      CIK      Founded
1      ABT           Abbott Laboratories  ...     1800         1888
7      AMD    Advanced Micro Devices Inc  ...     2488         1969
12     APD  Air Products & Chemicals Inc  ...     2969         1940
414   SWKS            Skyworks Solutions  ...     4127         2002
236    HWM              Howmet Aerospace  ...     4281         2016
..     ...                           ...  ...      ...          ...
497    XRX                         Xerox  ...  1770450         1906
355   OTIS                Otis Worldwide  ...  1781335  2020 (1853)
87    CARR                Carrier Global  ...  1783180  2020 (1915)
474    VNT                       Vontier  ...  1786842         2019
472   VTRS                       Viatris  ...  1792044         1961

[505 rows x 9 columns]

## Sort by name

In [4]:
sp500Companies.sort_values("Security")

    Symbol            Security SEC filings  ... Date first added      CIK Founded
0      MMM          3M Company     reports  ...       1976-08-09    66740    1902
43     AOS     A.O. Smith Corp     reports  ...       2017-07-26    91142    1916
3     ABMD         ABIOMED Inc     reports  ...       2018-05-31   815094    1981
9      AES            AES Corp     reports  ...       1998-10-02   874761    1981
10     AFL           AFLAC Inc     reports  ...       1999-05-28     4977    1955
..     ...                 ...         ...  ...              ...      ...     ...
501   ZBRA  Zebra Technologies     reports  ...       2019-12-23   877212    1969
502    ZBH       Zimmer Biomet     reports  ...       2001-08-07  1136869    1927
503   ZION       Zions Bancorp     reports  ...       2001-06-22   109380    1873
504    ZTS              Zoetis     reports  ...       2013-06-21  1555280    1952
161   EBAY           eBay Inc.     reports  ...              NaN  1065088    1995

[505 rows x 9 columns]

## Sort by founded

In [5]:
sp500Companies.sort_values("Founded")

    Symbol                     Security  ...      CIK      Founded
62      BK  The Bank of New York Mellon  ...  1390777         1784
421    STT           State Street Corp.  ...    93751         1792
116     CL            Colgate-Palmolive  ...    21665         1806
221    HIG   Hartford Financial Svc.Gp.  ...   874766         1810
122     ED          Consolidated Edison  ...  1047862         1823
..     ...                          ...  ...      ...          ...
26    AMCR                    Amcor plc  ...  1748790  2019 (1860)
279    LHX        L3Harris Technologies  ...   202058  2019 (1895)
471   VIAC                    ViacomCBS  ...   813828  2019 (1952)
355   OTIS               Otis Worldwide  ...  1781335  2020 (1853)
87    CARR               Carrier Global  ...  1783180  2020 (1915)

[505 rows x 9 columns]